### ISSUE TITLE
Run script for all users

### ISSUE THREAD

**Issue by neorai** [Raphire/Win11Debloat#149] opened 2024-10-28 14:57 UTC
**Is your feature request related to a problem? Please describe.**
I have a problem when running the script with administrator permissions on a domain user. The changes are made to the administrator account, not the current user.

**Describe the solution you'd like**
I want to be able to choose which user to run the script on or run it on all user profiles

**Comment by cyberbol** [comment] 2024-10-29 08:54
It works on 24H2 ?

**Comment by Raphire** [comment] 2024-10-31 20:27
Heya,

This seems like a duplicate of the issue described here: https://github.com/Raphire/Win11Debloat/issues/72

**Comment by Raphire** [comment] 2024-11-09 14:15
Closed as duplicate of #72

**Closed by Raphire** 2024-11-09 14:15 UTC
