### ISSUE TITLE
Youtube error message: "An error occurred. Please try again later." (Playback ID error.)

### ISSUE THREAD

**Issue by Vallex323** [Raphire/Win11Debloat#155] opened 2024-11-07 12:35 UTC
Hello,
When I click to start a youtube video for the first time, the following error message appears:
"An error occurred. Please try again later (Playback ID xxxxxx)”, where xxxxx is a random string of letters and numbers.
If I refresh the page with F5 key, the video starts correctly, but this message is kind of annoying...
I mention that I have Youtube Premium account.
This error occured after I installed ”Win11Debloat MAster” and I think that this app caused the problem, as it appeared on both the PC I installed it on (home PC and work PC).
Yhank you in advance for any support!
Vallex

**Comment by scheka** [comment] 2024-11-07 19:50
Hiello,

this has nothing to do with Win11Debloat. Have the same problem on Windows 10. Problem occurred randomly, now nearly every first attempt watching a video fails.

**Comment by Vallex323** [comment] 2024-11-07 19:57
@scheka, I think it has, I have windows11 on both the PC's I installed Win11Debloat, on both of them I get this error when I click on an Youtube video, I still got it some minutes ago

**Comment by Raphire** [comment] 2024-11-07 21:12
Heya,

I don't know of any way how this could be caused by the script. I certainly haven't run into this myself. 

I do see that this is an issue that has been reported before, and there seem to be some reports of it in recent few days. See: https://www.reddit.com/r/youtube/comments/1dlygfu/an_error_occurred_please_try_again_later_playback/

What browser are you using? Have you tried a different browser?

**Comment by Raphire** [comment] 2024-11-18 20:40
Closing issue due to lack of information. From the info provided I can't think of any way Win11Debloat could cause this issue.

**Closed by Raphire** 2024-11-18 20:40 UTC
