### ISSUE TITLE
Removal failed. Please contact your software vendor.

### ISSUE THREAD

**Issue by cheezypotatoes** [Raphire/Win11Debloat#74] opened 2024-06-25 01:27 UTC
What I did was just try to remove some stuff, and it pops up when the script tries to remove it.

**Comment by geeneeva** [comment] 2024-06-25 03:06
Happened to me, but it was a false positive. 

Check back with the same settings that you did. Press the Run BAT file, follow the prompts, go to App removal mode (option 3). When the application selection window pops up, check "Only show installed apps" on the bottom right corner. Here you can see whether or not it remove the apps.

I personally noticed it deleted most of the apps I asked it to except for Microsoft Edge. Hope this somewhat helps.

**Comment by Raphire** [comment] 2024-06-25 07:03
Did this error pop up for every app?

Additionally, do you know if any apps actually remained? The instructions @geeneeva posted above are a great way to find out.

**Comment by EliHedrick** [comment] 2024-06-25 19:26
> Did this error pop up for every app?
> 
> Additionally, do you know if any apps actually remained? The instructions @geeneeva posted above are a great way to find out.

Hi, personally I just experienced this on every app except for OneDrive and MSTeams. I ran the script again to see installed applications like geeneeva said, and they were all properly removed. I ran the batch file as admin on Win10.

PS. I actually didnt see an option to unselect MSTeams on the app selector so it was uninstalled! I actually needed that one on my pc haha

**Comment by Raphire** [comment] 2024-06-25 21:00
Interesting. Thanks for the information @EliHedrick 

@cheezypotatoes & @geeneeva are you guys running Windows 10 too?

**Comment by DmitryKashitsyn** [comment] 2024-06-25 21:32
Hey, got the same issue on Win 10. Same errors for everything except OneDrive. Also deleted almost everything. Except it didn't delete the app "Speed" without throwing any errors.
![image](https://github.com/Raphire/Win11Debloat/assets/126165920/054f4581-fbdc-46f8-869c-9c65379f7fa7)

**Comment by Raphire** [comment] 2024-06-25 21:59
@DmitryKashitsyn The plot thickens... 

Thanks for the information. Seems like I'll have to do some testing with W10! 🙃

**Comment by geeneeva** [comment] 2024-06-25 22:02
Yes, I'm running Windows10

**Comment by cheezypotatoes** [comment] 2024-06-26 01:27
> Interesting. Thanks for the information @EliHedrick 
> 
> @cheezypotatoes & @geeneeva are you guys running Windows 10 too?

Yeah

**Comment by Raphire** [comment] 2024-06-26 07:18
Thanks all for confirming. 

Unfortunately I'm not able to reproduce it with my W10 machine. Does anybody know the exact errorcode that was thrown? A screenshot of the error would be very helpful.

**Comment by sylvanuses** [comment] 2024-06-26 08:29
Tried, got an error, it does everything fine, just shows an error. win 10
Error code: 0x80070002. .\Win11Debloat-master\Win11Debloat.ps1:348 знак:52
+ ...   Get-AppxPackage -Name $app -AllUsers | Remove-AppxPackage -AllUsers
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Comman
   ds.RemoveAppxPackageCommand

**Comment by Raphire** [comment] 2024-06-26 10:17
@sylvanuses Thanks that does narrow things down. I do see multiple instances of people running into this into the past, but there's no clear indication what the root cause is. 

What Windows version are you running? You can check by pressing `Win + R` and typing in `winver`

This will pop-up a window like this: 
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/2e050a85-59a7-4cd0-85e2-ae95f752f264)

**Comment by bqback** [comment] 2024-06-27 07:47
Same issue, same error message as sylvanuses, running the exact version pictured in your screenshot .

**Comment by Raphire** [comment] 2024-06-27 11:21
I've pushed an update to change the way apps are removed on Windows 10 systems. 

This should prevent the issue, but I can't verify it myself as I'm unable to reproduce the error.

**Comment by Raphire** [comment] 2024-07-08 14:22
Closing this issue as there are no new reports of this since the fix issued in 2e967e5

If this issue does pop up again please feel free to reopen this issue or create a new one ;3

**Closed by Raphire** 2024-07-08 14:22 UTC
Labels: bug
