### ISSUE TITLE
"Disable & remove bing search & cortana in Windows search" breaks all forms of search

### ISSUE THREAD

**Issue by tig360** [Raphire/Win11Debloat#70] opened 2024-06-14 08:17 UTC
Selecting the option "Disable & remove bing search & cortana in Windows search." broke my search completely. I could not find any files or programs. It just kept loading and loading. I restored the functionality by running "Enable_Bing_Cortana_In_Search.reg" which fixed the issue after a reboot.

I am running Windows 11 v23H2.

**Comment by Raphire** [comment] 2024-06-14 22:14
Heya,

I'm unfortunately unable to reproduce this issue myself. Did you attempt a system restart after disabling search?

**Comment by tig360** [comment] 2024-06-18 18:12
I have just tried the script on my desktop (the previous try was on my laptop) and it worked just fine. Maybe the is something weird about the windows install on my laptop. Thanks anyway.

**Comment by Raphire** [comment] 2024-06-18 18:40
Thanks for the additional info. I did find some other user reports with a similar issue where rebuilding the Windows search index seems to help. See here for example: https://www.reddit.com/r/techsupport/comments/1bqk4pj/windows_search_function_is_giving_me_infinite/

I'll close this issue for now, but feel free to open a new issue if you find out more about the issue or encounter any other problems.

**Closed by Raphire** 2024-06-18 18:40 UTC
Labels: bug
