### ISSUE TITLE
Recalling saved options on next run does not remove pinned apps

### ISSUE THREAD

**Issue by wired-bc** [Raphire/Win11Debloat#57] opened 2024-05-13 15:47 UTC
A custom selection of removals saves a file - but when the script picks that file up on the next run the option to remove pinned apps from start menu is not applied.

**Comment by Raphire** [comment] 2024-05-14 07:35
Heya,

Clearing the start menu relies on replacing the startmenu binary with one provided by the script. 

Could you check if in the Win11debloat script folder there's still a folder called `Start` with a `start2.bin` file inside?

**Comment by Raphire** [comment] 2024-06-13 09:31
> Heya,
> 
> @wired-bc I am unfortunately unable to reproduce this issue myself, I do however have an idea what might be causing this.
> 
> Clearing the start menu relies on replacing the startmenu binary with one provided by the script. Could you check if in the Win11debloat script folder there's still a folder called `Start` with a `start2.bin` file inside?

@wired-bc

**Comment by Raphire** [comment] 2024-06-18 09:32
Closing issue due to lack of information to reproduce this issue. Feel free to open a new issue in the future if the issue persists.

**Closed by Raphire** 2024-06-18 09:32 UTC
Labels: bug
