### ISSUE TITLE
Microsoft Sticky Notes

### ISSUE THREAD

**Issue by mdixon1999** [Raphire/Win11Debloat#34] opened 2024-02-28 17:56 UTC
I would like to NOT have Microsoft Sticky Notes removed automatically.  I added the # before the entry in the Appslist text file, but it is still removed whenever I run the app.

I would also like the option to HIDE the Windows Copilot instead of removing it completely, at least for now while it is in Beta mode.  The problem is there is no standalone installer for Copilot so once it's gone the only way to get back is through a Microsoft Windows or Office Update currently.

**Comment by Raphire** [comment] 2024-02-29 22:02
Heya,

I am unfortunately unable to reproduce the first issue related to the app being removed even after adding the # symbol. Apps get removed and skipped as expected. Did you save the appslist.txt file before executing the script?

As for copilot. Currently Win11Debloat doesn't remove copilot. It disables the feature on a system wide level. To re-enable it use the registry file called Enable_Copilot.reg, which is included with the script in the Regfiles > Undo folder. You may have to restart your PC after running this reg file.

**Comment by mdixon1999** [comment] 2024-02-29 23:05
Ok.  I am not sure what is happening then.  I will try again the next time I build a new image.

Thank you very much for your efforts and your response!

**Comment by Raphire** [comment] 2024-03-01 08:50
You're welcome! I'll close this issue, but feel free to open a new issue in the future if you encounter any problems :)

**Closed by Raphire** 2024-03-01 08:50 UTC
