### ISSUE TITLE
The script goes on forever

### ISSUE THREAD

**Issue by Dylan96** [Raphire/Win11Debloat#137] opened 2024-10-02 18:55 UTC
**Describe the bug**
I have run this script on many Windows 11 workstations, some fully up to date, using the run.bat file and selecting the default option.
Sometimes the script just seems to run forever, hanging for 30-40 minutes just to uninstall the default selection of MS Store apps...

**To Reproduce**
1. Open 'Run.bat'
2. Select 'default selection of apps'
3. Wait for 'FOREVER'

**Expected behavior**
I guess it shouldn't take more than 10 minutes to complete.

**Screenshots**
None

**Additional context**

**Comment by Dylan96** [comment] 2024-10-04 18:30
After double-checking, some machines were indeed domain-joined at some point. Someone just removed them from the domain without deleting all the profiles.

Perhaps you could add an indication of which profile the current application is being removed from? so it doesn't look like it's stuck.

**Comment by prat7899** [comment] 2024-10-10 08:13
perhaps youu could add an indicator as usuabel and  do eomthing wrong

**Comment by Raphire** [comment] 2024-12-04 16:15
Closing this as a duplicate of https://github.com/Raphire/Win11Debloat/issues/140

**Closed by Raphire** 2024-12-04 16:15 UTC
Labels: bug
